---

# We need to convert the legacy inventory (all servers in test_instances
# group) to the new style with composer/workers groups.
- name: Migrate inventory to new format
  hosts: test_instances
  tasks:

    - name: Convert legacy inventory
      add_host:
        hostname: "{{ groups['test_instances'][0] }}"
        groups: "{{ item }}"
      loop:
        - composer
        - workers

- name: Deploy with remote workers
  hosts: "composer:workers"
  vars_files:
    - vars.yml
  pre_tasks:

    - name: Install ssh keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ item }}"
      loop: "{{ valid_ssh_keys }}"
      loop_control:
        label: "{{ item.split(' ') | last }}"

    - name: Set a password for the default user
      user:
        name: "{{ ansible_ssh_user }}"
        password: "{{ password_hashes[ansible_ssh_user] }}"
        update_password: always
      become: yes

  roles:
    - osbuild
