---

- name: CA » Create private key
  openssl_privatekey:
    path: /etc/osbuild-composer/ca.key
    size: 4096
    owner: _osbuild-composer
  become: yes

- name: CA » Create CSR
  openssl_csr:
    path: /tmp/ca.csr
    privatekey_path: /etc/osbuild-composer/ca.key
    digest: sha512
    organization_name: composer CA Certificate
    basic_constraints: "CA:TRUE"
    key_usage:
      - keyCertSign
      - cRLSign
      - digitalSignature
    owner: _osbuild-composer
  become: yes

- name: CA » Sign certificate
  openssl_certificate:
    csr_path: /tmp/ca.csr
    path: /etc/osbuild-composer/ca-crt.pem
    privatekey_path: /etc/osbuild-composer/ca.key
    provider: selfsigned
    selfsigned_digest: sha512
    selfsigned_not_after: "+3650s"
    selfsigned_not_before: "+0s"
    subject:
      commonName: "Image Builder Self-Signed Certificate"
    owner: _osbuild-composer
  become: yes

- name: composer » Create private key
  openssl_privatekey:
    path: /etc/osbuild-composer/composer-key.pem
    size: 4096
    owner: _osbuild-composer
  become: yes

- name: composer » Create CSR
  openssl_csr:
    path: /tmp/composer.csr
    privatekey_path: /etc/osbuild-composer/composer-key.pem
    digest: sha512
    subject:
      commonName: composer
    owner: _osbuild-composer
  become: yes

- name: composer » Sign certificate
  openssl_certificate:
    csr_path: /tmp/composer.csr
    path: /etc/osbuild-composer/composer-crt.pem
    privatekey_path: /etc/osbuild-composer/composer-key.pem
    ownca_path: /etc/osbuild-composer/ca-crt.pem
    ownca_privatekey_path: /etc/osbuild-composer/ca.key
    provider: ownca
    owner: _osbuild-composer
  become: yes

- name: worker » Create private key
  openssl_privatekey:
    path: /etc/osbuild-composer/worker-key.pem
    size: 4096
    owner: _osbuild-composer
  become: yes

- name: worker » Create CSR
  openssl_csr:
    path: /tmp/worker.csr
    privatekey_path: /etc/osbuild-composer/worker-key.pem
    digest: sha512
    subject:
      commonName: composer
    owner: _osbuild-composer
  become: yes

- name: worker » Sign certificate
  openssl_certificate:
    csr_path: /tmp/worker.csr
    path: /etc/osbuild-composer/worker-crt.pem
    privatekey_path: /etc/osbuild-composer/worker-key.pem
    ownca_path: /etc/osbuild-composer/ca-crt.pem
    ownca_privatekey_path: /etc/osbuild-composer/ca.key
    provider: ownca
    owner: _osbuild-composer
  become: yes