---

- name: Show details about the system
  debug:
    msg: |
      System details:
        - Hostname: "{{ ansible_hostname }}"
        - IP address: "{{ ansible_default_ipv4.address }}"
        - CPUs: "{{ ansible_processor_vcpus }}"
        - Arch: "{{ ansible_architecture }}"