---

- name: Deploy /etc/hosts configuration
  blockinfile:
    path: /etc/hosts
    block: |
      # Composer host
      {{ ansible_default_ipv4.address }} composer

      # Workers
      {% for worker_hostname in groups['workers'] %}
      {{ hostvars[worker_hostname].ansible_default_ipv4.address }} worker{{ loop.index0 }}
      {% endfor %}
  become: yes
