---

  # composer-cli seems to exit with a return code of 1 when everything is okay.
- name: Test composer-cli
  command: composer-cli status show
  become: yes
  register: composer_cli_test
  failed_when:
    - '"API server status" not in composer_cli_test.stdout'
  changed_when: false

- name: Show output
  debug:
    var: composer_cli_test.stdout
