---

- hosts: localhost
  tasks:

    - name: Set facts
      set_fact:
        workspace: "{{ lookup('env', 'workspace') | default(no) }}"

    - name: Check for test log
      stat:
        path: /tmp/composer_tests.log.xz
      register: composer_log_check

    - name: Copy test logs where jenkins can pick them up
      copy:
        src: /tmp/composer_tests.log.xz
        dest: "{{ workspace }}/"
        remote_src: yes
      when:
        - composer_log_check.stat.exists
        - workspace | bool